services:
  # React app service
  react-app:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: react-app
    restart: always
    expose:
      - "3001"  # Expose React app on port 3001 internally
    ports:
      - "3001:3001"

  # Flask API service
  flask-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: flask-api
    restart: always
    environment:
      - FLASK_ENV=production
      - DB_USER=myuser
      - DB_PASS=mypassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
    ports:
      - "5000:5000"  # Flask API will be served on port 5000
    depends_on:
      - db

  # PostgreSQL database service
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "81:81"  # Expose port 81 for external access
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./server/files:/app/server/files
    depends_on:
      - react-app
      - flask-api

volumes:
  postgres-data:
